create table if not exists public.members (
  telegram_user_id text primary key,
  display_name text not null default '',
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_requests (
  telegram_user_id text primary key,
  display_name text not null default '',
  received_at timestamptz not null default now()
);

create table if not exists public.customer_messages (
  id bigint generated always as identity primary key,
  telegram_user_id text not null references public.payment_requests(telegram_user_id) on delete cascade,
  message_type text not null check (message_type in ('text', 'photo', 'document')),
  body text not null default '',
  file_id text not null default '',
  received_at timestamptz not null default now()
);

create index if not exists customer_messages_user_time_idx
  on public.customer_messages (telegram_user_id, received_at desc);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  is_live boolean not null default true,
  authorized boolean not null default false,
  league text not null default 'FOOTBALL LIVE',
  home text not null,
  away text not null default '',
  home_logo text not null default '',
  away_logo text not null default '',
  time_label text not null default 'LIVE NOW',
  stream_type text not null default 'hls' check (stream_type in ('hls', 'youtube')),
  stream_url text not null,
  updated_at timestamptz not null default now()
);

alter table public.members enable row level security;
alter table public.payment_requests enable row level security;
alter table public.customer_messages enable row level security;
alter table public.matches enable row level security;

insert into public.matches (id, is_live, authorized, league, home, away, home_logo, away_logo, time_label, stream_type, stream_url)
values (
  1, true, true, 'UEFA CHAMPIONS LEAGUE', 'Paris Saint-Germain', 'Aston Villa',
  'https://a.espncdn.com/i/teamlogos/soccer/500/19258.png',
  'https://cdn.freebiesupply.com/logos/large/2x/aston-villa-fc-01-logo-png-transparent.png',
  'LIVE NOW', 'hls', 'https://popwellfox.s3.us-east-1.amazonaws.com/rangers.m3u8'
)
on conflict (id) do update set
  is_live = excluded.is_live, authorized = excluded.authorized, league = excluded.league,
  home = excluded.home, away = excluded.away, home_logo = excluded.home_logo,
  away_logo = excluded.away_logo, time_label = excluded.time_label,
  stream_type = excluded.stream_type, stream_url = excluded.stream_url, updated_at = now();
